'use client';

import React from 'react';
import { Newsletter } from '@/store/newsletter';
import { cn } from '@/lib/utils';

interface NewsletterPreviewProps {
  newsletter: Newsletter;
  className?: string;
}

export function NewsletterPreview({ newsletter, className }: NewsletterPreviewProps) {
  return (
    <div
      className={cn(
        'bg-white text-gray-900 rounded-lg shadow-sm border border-gray-200 max-w-2xl mx-auto',
        className
      )}
      id="newsletter-preview"
    >
      {/* Header with template image */}
      {newsletter.templateImage && (
        <div className="w-full h-48 overflow-hidden rounded-t-lg">
          <img
            src={newsletter.templateImage}
            alt="Newsletter header"
            className="w-full h-full object-cover"
          />
        </div>
      )}

      <div className="px-8 py-6">
        {/* Headline */}
        <h1 className="text-2xl font-serif font-bold text-gray-900 mb-2">
          {newsletter.headline || newsletter.title}
        </h1>

        {/* Intro */}
        {newsletter.intro && (
          <p className="text-sm text-gray-600 leading-relaxed mb-6 border-b border-gray-100 pb-6">
            {newsletter.intro}
          </p>
        )}

        {/* Sections */}
        {newsletter.sections.map((section) => (
          <div key={section.id} className="mb-6">
            <h2 className="text-lg font-serif font-semibold text-gray-800 mb-2 border-l-4 border-blue-500 pl-3">
              {section.heading}
            </h2>
            <div className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap pl-4">
              {section.body.split(/\*\*(.*?)\*\*/g).map((part, i) =>
                i % 2 === 1 ? (
                  <strong key={i}>{part}</strong>
                ) : (
                  <span key={i}>
                    {part.split(/\*(.*?)\*/g).map((sub, j) =>
                      j % 2 === 1 ? <em key={j}>{sub}</em> : sub
                    )}
                  </span>
                )
              )}
            </div>
          </div>
        ))}

        {/* Conclusion */}
        {newsletter.conclusion && (
          <div className="mt-6 pt-6 border-t border-gray-100">
            <p className="text-sm text-gray-600 leading-relaxed italic">
              {newsletter.conclusion}
            </p>
          </div>
        )}

        {/* Footer */}
        <div className="mt-8 pt-4 border-t border-gray-200 text-center">
          <p className="text-[11px] text-gray-400">
            Generated by EHCore — {new Date(newsletter.updatedAt).toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  );
}
